name: Deploy to Environments

on:
  push:
    branches:
      - master  # Trigger on push to master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your.email@example.com"

      - name: Deploy HTML file to Dev
        run: |
          echo "Deploying to Dev environment"
          git fetch origin  # Fetch branches from the remote
          git checkout dev  # Check out the dev branch
          mkdir -p ./dev    # Create the dev directory if it doesn't exist
          cp index.html ./dev/index.html
          git add dev/index.html
          git commit -m "Deploy to Dev"
          git push origin dev || echo "Failed to push to dev branch"
          
      - name: Deploy HTML file to Prod
        run: |
          echo "Deploying to Prod environment"
          git checkout master
          mkdir -p ./prod
          cp index.html ./prod/index.html
          git add prod/index.html
          git commit -m "Deploy to Prod"
          git push origin master || echo "Failed to push to master branch"
  
